### ISSUE TITLE
Topg voting didnt work

### ISSUE THREAD

**Issue by Jager67** [UpcraftLP/Voting#6] opened 2018-11-19 14:28 UTC
08:24:36Votifier: incorrect vote received:
Console 11/19/2018 08:24:36
08:24:36-----------------------------------------------------
VOTE
TopG.org
Tz_Jager
252.197.208.95
1542637476

-----------------------------------------------------
Vote-Listener/ERROR 11/19/2018 08:24:36
08:24:36invalid vote timestamp!
Console 11/19/2018 08:24:36
08:24:36java.text.ParseException: Unparseable date: "1542637476"
at java.text.DateFormat.parse(DateFormat.java:366) ~[?:1.8.0_181]
at com.github.upcraftlp.votifier.net.NetworkListenerThread.run(NetworkListenerThread.java:59) [NetworkListenerThread.class:1.0.0]
Vote-Listener/ERROR 11/19/2018 08:25:36
08:25:36Error handling socket connection!
Console 11/19/2018 08:25:36
08:25:36javax.crypto.BadPaddingException: Decryption error
at sun.security.rsa.RSAPadding.unpadV15(RSAPadding.java:383) ~[?:1.8.0_181]
at sun.security.rsa.RSAPadding.unpad(RSAPadding.java:294) ~[?:1.8.0_181]
at com.sun.crypto.provider.RSACipher.doFinal(RSACipher.java:363) ~[sunjce_provider.jar:1.8.0_171]
at com.sun.crypto.provider.RSACipher.engineDoFinal(RSACipher.java:389) ~[sunjce_provider.jar:1.8.0_171]
at javax.crypto.Cipher.doFinal(Cipher.java:2164) ~[?:1.8.0_171]
at com.github.upcraftlp.votifier.util.RSAUtil.decrypt(RSAUtil.java:28) ~[RSAUtil.class:1.0.0]
at com.github.upcraftlp.votifier.net.NetworkListenerThread.run(NetworkListenerThread.java:47) [NetworkListenerThread.class:1.0.0]

**Comment by 132ikl** [comment] 2018-11-19 20:49
Update mod version to 1.2.0

**Comment by UpcraftLP** [comment] 2018-11-19 20:54
duplicate of #3

**Closed as completed by UpcraftLP** 2018-11-19 20:54 UTC
Labels: duplicate
