### ISSUE TITLE
It will not work on the site I know

### ISSUE THREAD

**Issue by myaako-wasure** [UpcraftLP/Voting#5] opened 2018-10-29 07:56 UTC
If you try to enable voting on this site, an error will be output.
https://minecraft.jp/en/
```
[16:52:37] [Vote-Listener/ERROR] [votifier]: Error handling socket connection!
javax.crypto.BadPaddingException: Decryption error
	at sun.security.rsa.RSAPadding.unpadV15(RSAPadding.java:383) ~[?:1.8.0_191]
	at sun.security.rsa.RSAPadding.unpad(RSAPadding.java:294) ~[?:1.8.0_191]
	at com.sun.crypto.provider.RSACipher.doFinal(RSACipher.java:363) ~[sunjce_provider.jar:1.8.0_191]
	at com.sun.crypto.provider.RSACipher.engineDoFinal(RSACipher.java:389) ~[sunjce_provider.jar:1.8.0_191]
	at javax.crypto.Cipher.doFinal(Cipher.java:2164) ~[?:1.8.0_191]
	at com.github.upcraftlp.votifier.util.RSAUtil.decrypt(RSAUtil.java:27) ~[RSAUtil.class:1.2.0]
	at com.github.upcraftlp.votifier.net.NetworkListenerThread.run(NetworkListenerThread.java:48) [NetworkListenerThread.class:1.2.0]
[16:52:37] [Vote-Listener/ERROR] [votifier]: Error handling socket connection!
javax.crypto.BadPaddingException: Decryption error
	at sun.security.rsa.RSAPadding.unpadV15(RSAPadding.java:383) ~[?:1.8.0_191]
	at sun.security.rsa.RSAPadding.unpad(RSAPadding.java:294) ~[?:1.8.0_191]
	at com.sun.crypto.provider.RSACipher.doFinal(RSACipher.java:363) ~[sunjce_provider.jar:1.8.0_191]
	at com.sun.crypto.provider.RSACipher.engineDoFinal(RSACipher.java:389) ~[sunjce_provider.jar:1.8.0_191]
	at javax.crypto.Cipher.doFinal(Cipher.java:2164) ~[?:1.8.0_191]
	at com.github.upcraftlp.votifier.util.RSAUtil.decrypt(RSAUtil.java:27) ~[RSAUtil.class:1.2.0]
	at com.github.upcraftlp.votifier.net.NetworkListenerThread.run(NetworkListenerThread.java:48) [NetworkListenerThread.class:1.2.0]
[16:52:37] [Vote-Listener/ERROR] [votifier]: Error handling socket connection!
javax.crypto.BadPaddingException: Decryption error
	at sun.security.rsa.RSAPadding.unpadV15(RSAPadding.java:383) ~[?:1.8.0_191]
	at sun.security.rsa.RSAPadding.unpad(RSAPadding.java:294) ~[?:1.8.0_191]
	at com.sun.crypto.provider.RSACipher.doFinal(RSACipher.java:363) ~[sunjce_provider.jar:1.8.0_191]
	at com.sun.crypto.provider.RSACipher.engineDoFinal(RSACipher.java:389) ~[sunjce_provider.jar:1.8.0_191]
	at javax.crypto.Cipher.doFinal(Cipher.java:2164) ~[?:1.8.0_191]
	at com.github.upcraftlp.votifier.util.RSAUtil.decrypt(RSAUtil.java:27) ~[RSAUtil.class:1.2.0]
	at com.github.upcraftlp.votifier.net.NetworkListenerThread.run(NetworkListenerThread.java:48) [NetworkListenerThread.class:1.2.0]
```
On another site it worked normally.
https://mctools.org/votifier-tester
```
[16:54:33] [Server thread/INFO] [votifier]: [1540799671] received vote from rkcyk706 (service: MCTools.org)
```

**Comment by UpcraftLP** [comment] 2018-11-19 20:55
duplicate of #2

**Closed as completed by UpcraftLP** 2018-11-19 20:55 UTC
Labels: duplicate
